<?php
//added to DB
//privacy
$privacy_text = "בחר/י את המשתמשים ואת הקבוצות אשר תרצה/י לאפשר להם לעיין בפרטים שלך";

//security
$security_text = "Save הקלד / הקלידי את הסיסמה שלך ומלא/י את השדות שברצונך לשנות ולחץ/י על ";
$security_current_password = "סיסמה נוכחית";
$security_new_password = "סיסמה חדשה";
$security_confirm_password = "אשר/י סיסמה";
$security_new_authcode = "קוד הרשאה חדש";
$security_confirm_authcode = "אשר/י קוד הרשאה";
$security_question = "בחר/י שאלה";
$security_answer = "ענה/י";
$security_wrong_password = "סיסמה שגויה.";
$security_tasks = "משימות הושלמו";
$security_password_update = "סיסמה עודכנה.";
$security_authcode_update = "קודים של הרשאות עודכנו.";
$security_question_update = "שאלה ותשובה עודכנו.";
$security_question_fail = "לא מילאת הן שאלה והן תשובה.";
$strBusinessNum = "מספר עסק";
$strZehut = "תעודת זהות";
 
$acProfile = "פרופיל";
$acSecurity = "אבטחה";
$acPrivacy = "פרטיות";
$acManager = "החשבון שלך";
$acStatistics = "סטטיסטיקה";
$acProfileText = " על מנת לשנות את הפרופיל שלך. השדות המסומנים ב- * הם הכרחיים.'Save'לחץ/י על ";
$acTitle ="החשבון שלך";
$ac_login_info = "נתוני כניסה למערכת";
$ac_registration_time = "זמן רישום";
$ac_lastlogin = "הכניסה האחרונה למערכת";
$ac_logins = "סה''כ כניסות";
$ac_disk_usage = "שימוש בדיסק";
$ac_max_diskspace = "נפח דיסק מרבי";
$ac_available_diskspace = "נפח דיסק זמין";
$ac_used_diskspace = "נפח דיסק בשימוש";
$ac_used = "בשימוש";

//privacy
$lang['privacy_text'] = "בחר/י את המשתמשים ואת הקבוצות אשר תרצה/י לאפשר להם לעיין בפרטים שלך";

//security
$lang['security_text'] = "Save הקלד / הקלידי את הסיסמה שלך ומלא/י את השדות שברצונך לשנות ולחץ/י על ";
$lang['security_current_password'] = "סיסמה נוכחית";
$lang['security_new_password'] = "סיסמה חדשה";
$lang['security_confirm_password'] = "אשר/י סיסמה";
$lang['security_new_authcode'] = "קוד הרשאה חדש";
$lang['security_confirm_authcode'] = "אשר/י קוד הרשאה";
$lang['security_question'] = "בחר/י שאלה";
$lang['security_answer'] = "ענה/י";
$lang['security_wrong_password'] = "סיסמה שגויה.";
$lang['security_tasks'] = "משימות הושלמו";
$lang['security_password_update'] = "סיסמה עודכנה.";
$lang['security_authcode_update'] = "קודים של הרשאות עודכנו.";
$lang['security_question_update'] = "שאלה ותשובה עודכנו.";
$lang['security_question_fail'] = "לא מילאת הן שאלה והן תשובה.";
$lang['strBusinessNum'] = "מספר עסק";
$lang['strZehut'] = "תעודת זהות";

$lang['acProfile'] = "פרופיל";
$lang['acSecurity'] = "אבטחה";
$lang['acPrivacy'] = "פרטיות";
$lang['acManager'] = "החשבון שלך";
$lang['acStatistics'] = "סטטיסטיקה";
$lang['acProfileText'] = " על מנת לשנות את הפרופיל שלך. השדות המסומנים ב- * הם הכרחיים.'Save'לחץ/י על ";
$lang['acTitle'] ="החשבון שלך";
$lang['ac_login_info'] = "נתוני כניסה למערכת";
$lang['ac_registration_time'] = "זמן רישום";
$lang['ac_lastlogin'] = "הכניסה האחרונה למערכת";
$lang['ac_logins'] = "סה''כ כניסות";
$lang['ac_disk_usage'] = "שימוש בדיסק";
$lang['ac_max_diskspace'] = "נפח דיסק מרבי";
$lang['ac_available_diskspace'] = "נפח דיסק זמין";
$lang['ac_used_diskspace'] = "נפח דיסק בשימוש";
$lang['ac_used'] = "בשימוש";

?>
