<?
$direction = 'rtl';
$charset = 'UTF-8';

$lang['strCopyright'] = "כול הזכויות שמורות &copy; YedaTop תוכנות בע\"מ 2009. עזרה: 072-2125588"; 

$lang_modules['scheduler'] = "יומן";
$lang_modules['filesystem'] = 'קבצים';
$lang_modules['email'] = 'דואר אלקטרוני';
$lang_modules['projects'] = 'פרוייקטים';
$lang_modules['realty'] = 'משרד מתווך';
$lang_modules['catalog_admin'] = 'ניהול ראשי של קטלוג עסקים';
$lang_modules['catalog'] = 'קטלוג עסקים';
//$lang_modules['stock'] = 'מלאיטק';
$lang_modules['stock'] = 'YedaTop';
$lang_modules['stock_admin'] = 'ניהול YedaTop';
$lang_modules['stock_reports'] = 'YedaTop דוחות';
$lang_modules['stocktaking'] = 'ספירת מלאי';
$lang_modules['account'] = 'החשבון שלך';
$lang_modules['shaon'] = 'שעון נוכחות';
$lang_modules['credit'] = 'מכירה בהקפה - קופות רושמות';
$lang_modules['credit2'] = 'מכירה בהקפה';
$lang_modules['stock_clients'] = 'YedaTop לקוחות';
$lang_modules['stock_cashbox'] = 'YedaTop קופה';
$lang_modules['stock_crm'] = 'YedaTop CRM';
$lang_modules['stock_pro'] = 'YedaTop פרו'; 

$current_language="he"; 


//main language menu file register login and other non logged in pages
//common
$lang['cmdLogin'] = "כניסה";
$lang['cmdSave'] = "שמור";
$lang['cmdBack'] = "חזרה";
$lang['cmdCancel'] = "ביטול";
$lang['cmdClose'] = "סגור";
$lang['cmdOk'] = "אישור";
$lang['cmdDelete'] = "מחק";
$lang['cmdNext'] = "קדימה";
$lang['cmdPrevious'] = "אחורה";
$lang['cmdContinue'] = "המשך";
$lang['cmdUpdate'] = "לסנכרן";
$lang['cmdApply'] = "ליישם";
$lang['cmdJoin'] = "משתמש חדש? פתח משרד שלך עכשיו!";
$lang['cmdYes'] = "כן";
$lang['cmdNo'] = "לא";
$lang['cmdAdd'] = 'הסף';
$lang['cmdEdit'] = 'שינוי';
$lang['cmdInvertSelection'] = 'invert selection';

$lang['strEdit'] = "ערוך";
$lang['strThis'] = 'זה';
$lang['strItems'] = 'פריטים';
$lang['strFrom'] ='מ';
$lang['strName'] = "שם";
$lang['strUser'] = "משתמש";
$lang['strUsername'] = "שם משתמש";
$lang['strPassword'] = "סיסמה";
$lang['strAuthcode'] = "קוד הרשאה";
$lang['strCountry'] = "ארץ";
$lang['strState'] = "מדינה";
$lang['strCity'] = "עיר";
$lang['strZip'] = "מיקוד";
//$lang['strBusinessNum'] = "מספר עסק";
//$lang['strZehut'] = "תעודת זהות";
$lang['strAddress'] = "רחוב"; 
$lang['strEmail'] = "דואר אלקטרוני";
$lang['strPhone'] = "טלפון";
$lang['strWorkphone'] = "טלפון בעבודה";
$lang['strCellular'] = "טלפון נייד";
$lang['strCompany'] = "חברה";
$lang['strDepartment'] = "מחלקה";
$lang['strFunction'] = "תפקיד";
$lang['strQuestion'] = "שאלה סודית";
$lang['strAnswer'] = "תשובה";
$lang['strFax'] = "פקס";
$lang['strWorkFax'] = "פקס בעבודה";
$lang['strHomepage'] = "דף בית";
$lang['strWorkAddress'] = "כתובת בעבודה";
$lang['strWorkZip'] = "מיקוד בעבודה";
$lang['strWorkCountry'] = "Country work";
$lang['strWorkState'] = "בשירת המדינה";
$lang['strWorkCity'] = "עבודה בעיר";
$lang['strPhoto'] = "תמונה";
$lang['strComments'] = "הערות";

$lang['strProperties'] = 'תכונות';

$lang['strDeleteItem'] = "מחק";

$lang['strDate'] = "תאריך";

$lang['strSaveSuccess'] = "הנתונים נשמרו בהצלחה";
$lang['strSaveError'] = "התרחשה טעות בעת שמירת הנתונים. אנא נסה/י שנית.";
$lang['strDataError'] = "התרחשה טעות בעת קריאת הנתונים. אנא נסה/י שנית";
$lang['strDeleteError'] = "מחיקת נתונים לא התאפשרה.";
$lang['strAclError'] = "טעות בבקרת כניסה";
$lang['strDateError'] = "הקלדת תאריך שגוי";



$lang['strAccessDenied'] = "הגישה נדחית";
$lang['AccessDenied_text'] = "משתמש אחר הגביל את הגישה למידע שביקשת.<br< אינך רשאי/ת לעיין בקטע זה של האתר או לבצע פעולה זו. ";

$lang['invalid_chars'] = "התווים הבאים אינם מותרים";

$lang['strGroups'] = "קבוצות";
$lang['strOwner'] = "בעלים";

$lang['strDeletePrefix'] = "האם את/ה בטוח/ה שברצונך למחוק ";
$lang['strDeleteSuffix'] = "?";

//menu
$lang['menu_logout'] = "יציאה מהמערכת";
$lang['menu_applications'] = "יישומים";
$lang['menu_help'] = "עזרה";
$lang['menu_about'] = "אודות";
$lang['menu_documentation'] = "תיעוד";
$lang['menu_configuration'] = "תצורה";
$lang['menu_groups'] = "קבוצות משתמשים";
$lang['menu_accounts'] = "החשבון שלך";
$lang['menu_preferences'] = "עדיפויות";
$lang['menu_bookmarks'] = "סימניות";
$lang['menu_bookmarks_manage'] = "סימניות&nbsp;שנה/י";
$lang['menu_add_bookmark'] = "הוסף סימניה";
$lang['menu_add_current'] = "הוסיף עמוד נוכחי";
$lang['menu_contacts'] = "ספר כתובות";
$lang['menu_invite'] = "הזמן משתמשים";
$lang['menu_search'] = "חפש";
$lang['menu_search_discussions'] = "דיונים";
$lang['menu_search_files'] = "קבצים ו-תיקיות";
$lang['menu_search_web'] = "the&nbsp;web";
$lang['menu_scheduler'] = "קובע לו''ז";
$lang['menu_filetypes'] = "סוגי קבצים";
$lang['menu_discussions'] = "לוח דיונים";

$lang['menu_users'] = "משתמשים";
$lang['menu_start'] = "שולחן עבודה";
//$lang['start'] = "התחלה";
$lang['menu_reboot'] = "reboot&nbsp;server";
$lang['menu_halt'] = "shutdown&nbsp;server";
$lang['menu_reboot_text'] = "לא יהיו נגישים זמנית. האם את/ה בטוח/ה שברצונך להמשיך? NetCityBIZ Officeהזהרה! כל שירותי ";
$lang['menu_halt_text'] = "יפסיקו את פעולתם. האם את/ה בטוח/ה שברצונך להמשיך? NetCityBIZ Office הזהרה! כל שירותי ";
$lang['menu_new'] = "חדש";
$lang['menu_message'] = "הודעה";
$lang['menu_contact'] = "קשר";
$lang['menu_event'] = "אירוע";
$lang['menu_bookmark'] = "סמנייה";
$lang['menu_topics'] = "נושאים";
$lang['menu_support'] = "תמיכה";
$lang['menu_projects'] = "פרוייקטים";
$lang['menu_sysinfo'] = "מידע על המערכת";
$lang['menu_admin'] = 'administrator';
$lang['menu_modules'] = 'מודולים';
$lang['menu_manual'] = 'עזרה';

//class validate
$lang['error_required'] = ".לא פירטת את השדה הדרוש למטה ";
$lang['error_match_auth'] = "הקודים של הרשאה לא תאמו.";
$lang['error_match_pass'] = "הסיסמאות לא תאמו";
$lang['error_min_length'] = "המספר המינימלי של התווים בשדה למטה הוא...";
$lang['error_max_length'] = "המספר המרבי של התווים בשדה למטה הוא...";
$lang['error_email'] = "כתובת הדואר האלקטרונית שציינת אינה פעילה.";
$lang['error_email_exists'] = "כתובת הדואר האלקטרונית שציינת כבר קיימת.";
$lang['error_username_exists'] = "שם המשתמש שהקלדת כבר קיים, עמך הסליחה. אנא בחר/י שם משתמש אחר.";
$lang['errors_in_form'] = "נעשו טעויות בעת מילוי הטופס. אנא תקן/י אותן ונסה/י שנית.";
$lang['error_missing_field'] = "לא מילאת את כל השדות הדרושים.";

//acl control
$lang['acl_control_auth_groups'] = "קבוצות מורשות";
$lang['acl_control_auth_users'] = "משתמשים מורשים";
$lang['acl_control_no_contacts'] = "אין לך אנשי קשר לבחירה.<br /> השתמש בספר כתובות על מנת להוסיף חברים לאנשי הקשר שלך";

$lang['strShowProfile'] = "עיין בפרופיל";
$lang['strShowGroup'] = "עיין בחברי קבוצה";
$lang['strProcessingTime'] = "עיבוד של דף זה לקח ";
$lang['strLoggedInAs'] = "נכנסת כ- ";
$lang['strAt'] = " ב- ";
$lang['strEmailTo'] = "שלח הודעה אלקטרונית ל- ";
$lang['strProtectedUser'] = "משתמש מוגן או משתמש בלי זיהוי במערכת";

$lang['http_not_found'] = "המסמך לא נמצא";
$lang['http_not_found_text'] = "המסמך שביקשת אינו נמצא. ייתכן שטעית בהקלדת ה- URL.";
$lang['http_error'] = "טעות שרת פנימית";
$lang['http_bad_request'] = "הבקשה אינה קבילה";
$lang['strAddContact'] = "הוסף לאנשי קשר";

$lang['strReadRights'] = "קרא הרשאות";
$lang['strWriteRights'] = "כתוב הרשאות";
$lang['strPermissions'] = 'הרשאות';

$lang['editor_bold'] = "מודגש";
$lang['editor_italic'] = "נטוי";
$lang['editor_underline'] = "קו תחתון";
$lang['editor_left'] = "שמאלי";
$lang['editor_right'] = "ימני";
$lang['editor_center'] = "מרכזי";
$lang['editor_ord_list'] = "רשימת הזמנות";
$lang['editor_bul_list'] = "רשימת מובלטים";
$lang['editor_txt_color'] = "צבע טקסט";
$lang['editor_back_color'] = "צבע רקע";
$lang['editor_hyperlink'] = "Hyperlink";
$lang['editor_image'] = "דמות";
$lang['editor_rule'] = "סרגל אופקי";

$lang['editor_very_small'] = "קטן מאוד";
$lang['editor_small'] = "קטן";
$lang['editor_medium'] = "בינוני";
$lang['editor_large'] = "גדול";
$lang['editor_larger'] = "גדול יותר";
$lang['editor_very_large'] = "גדול מאוד";

$lang['editor_strikethrough'] = "קו חוצה";
$lang['editor_outdent'] = "סטייה החוצה";
$lang['editor_indent'] = "כניסת טקסט";

$lang['editor_superscript'] = "כתב עילי";
$lang['editor_subscript'] = "כתב תחתי";
$lang['editor_undo'] = "בטל פעולה";
$lang['editor_redo'] = "בצע שוב";
$lang['editor_copy'] = "העתק";
$lang['editor_paste'] = "הדבק";
$lang['editor_cut'] = "גזור";

$lang['editor_font'] = "גופן";
$lang['editor_size'] = "גודל";
$lang['editor_heading'] = "כותרת";
$lang['editor_select'] = "בחר";

$lang['editor_mode'] = "הפעל מצב עריכה";

$days[0]="א'";
$days[1]="ב'";
$days[2]="ג'";
$days[3]="ד'";
$days[4]="ה'";
$days[5]="ו'";
$days[6]="ש";

$months[0]="ינואר";
$months[1]="פברואר";
$months[2]="מרץ";
$months[3]="אפריל";
$months[4]="מאי";
$months[5]="יוני";
$months[6]="יולי";
$months[7]="אוגוסט";
$months[8]="ספטמבר";
$months[9]="אוקטובר";
$months[10]="נובמבר";
$months[11]="דצמבר";

$full_days[0] = "יום א";
$full_days[1] = "יום ב";
$full_days[2] = "יום ג";
$full_days[3] = "יום ד";
$full_days[4] = "יום ה";
$full_days[5]= "יום ו";
$full_days[6] = "שבת";

$lang['register'] = "הרשמת משתמש חדש";
$lang['forgot_password'] = "שכחת סיסמה?"


?>