<?php
//added to DB
//privacy
$privacy_text = "Select the users and groups that you want to be visible to.";

//security
$security_text = "Enter your password and the fields you want to change and click on 'Save'.";
$security_current_password = "Current password";
$security_new_password = "New password";
$security_confirm_password = "Confirm password";
$security_new_authcode = "New authorisation code";
$security_confirm_authcode = "Confirm authorisation code";
$security_question = "Secret question";
$security_answer = "Answer";
$security_wrong_password = "Wrong password.";
$security_tasks = "Tasks completed";
$security_password_update = "Password updated.";
$security_authcode_update = "Authorisation codes updated.";
$security_question_update = "Question and answer updated.";
$security_question_fail = "You didn't fill in both the question and the answer.";
$strBusinessNum = "Business number";
$strZehut = "Identity card";


$acProfile = "Profile";
$acSecurity = "Security";
$acPrivacy = "Privacy";
$acManager = "Your Account";
$acStatistics = "Statistics";
$acProfileText = "Click on 'Save' to change your profile. The fields marked with a * are required.";
$acTitle = "Your Account";
$ac_login_info = "Login information";
$ac_registration_time = "Registration time";
$ac_lastlogin = "Last login";
$ac_logins = "Total logins";
$ac_disk_usage = "Disk Usage";
$ac_max_diskspace = "Maximum Diskspace";
$ac_available_diskspace = "Available Diskspace";
$ac_used_diskspace = "Used Diskspace";
$ac_used = "used";


//privacy
$lang['privacy_text'] = "Select the users and groups that you want to be visible to.";

//security
$lang['security_text'] = "Enter your password and the fields you want to change and click on 'Save'.";
$lang['security_current_password'] = "Current password";
$lang['security_new_password'] = "New password";
$lang['security_confirm_password'] = "Confirm password";
$lang['security_new_authcode'] = "New authorisation code";
$lang['security_confirm_authcode'] = "Confirm authorisation code";
$lang['security_question'] = "Secret question";
$lang['security_answer'] = "Answer";
$lang['security_wrong_password'] = "Wrong password.";
$lang['security_tasks'] = "Tasks completed";
$lang['security_password_update'] = "Password updated.";
$lang['security_authcode_update'] = "Authorisation codes updated.";
$lang['security_question_update'] = "Question and answer updated.";
$lang['security_question_fail'] = "You didn't fill in both the question and the answer.";
$lang['strBusinessNum'] = "Business number";
$lang['strZehut'] = "Identity card";


$lang['acProfile'] = "Profile";
$lang['acSecurity'] = "Security";
$lang['acPrivacy'] = "Privacy";
$lang['acManager'] = "Your Account";
$lang['acStatistics'] = "Statistics";
$lang['acProfileText'] = "Click on 'Save' to change your profile. The fields marked with a * are required.";
$lang['acTitle'] = "Your Account";
$lang['ac_login_info'] = "Login information";
$lang['ac_registration_time'] = "Registration time";
$lang['ac_lastlogin'] = "Last login";
$lang['ac_logins'] = "Total logins";
$lang['ac_disk_usage'] = "Disk Usage";
$lang['ac_max_diskspace'] = "Maximum Diskspace";
$lang['ac_available_diskspace'] = "Available Diskspace";
$lang['ac_used_diskspace'] = "Used Diskspace";
$lang['ac_used'] = "used";
?>
