<?php
$charset = 'ISO-8859-1';

$lang['strCopyright'] = "All rights reserved &copy; MlaiTech Ltd. 2009. Support: 072-2125588";  

$lang_modules['scheduler'] = "scheduler";
$lang_modules['filesystem'] = 'files';
$lang_modules['email'] = 'e-mail';
$lang_modules['projects'] = 'projects';
$lang_modules['realty'] = 'realty broker';
$lang_modules['stock'] = 'YedaTop';
$lang_modules['catalog_admin'] = 'Business catalog administration';
$lang_modules['catalog'] = 'Business catalog';
$lang_modules['stock_admin'] = 'YedaTop administration';
$lang_modules['stock_reports'] = 'YedaTop reports';
$lang_modules['account'] = 'Your account';
$lang_modules['shaon'] = 'Attendance log';
$lang_modules['credit'] = 'Credit Sales - Registered Cashiers';
$lang_modules['credit2'] = 'Credit Clients';
$lang_modules['stock_pro'] = 'YedaTop-Pro';
                                                                   
$current_language="en";

//main language menu file register login and other non logged in pages
//common
$lang['cmdLogin'] = "Login";
$lang['cmdJoin'] = "Not registered? Open your own office now!";
$lang['cmdSave'] = "save";
$lang['cmdBack'] = "back";
$lang['cmdCancel'] = "cancel";
$lang['cmdClose'] = "close";
$lang['cmdOk'] = "ok";
$lang['cmdDelete'] = "Delete";
$lang['cmdNext'] = "next";
$lang['cmdPrevious'] = "previous";
$lang['cmdContinue'] = "continue";
$lang['cmdUpdate'] = "synchronize";
$lang['cmdApply'] = "apply";
$lang['cmdYes'] = "yes";
$lang['cmdNo'] = "no";
$lang['cmdAdd'] = 'add';
$lang['cmdEdit'] = 'edit';
$lang['cmdInvertSelection'] = 'invert selection';

$lang['strFrom'] = "from";
$lang['strEdit'] = "Edit";
$lang['strThis'] = 'this';
$lang['strItems'] = 'items';

$lang['strName'] = "Name";
$lang['strUser'] = "User";
$lang['strUsername'] = "Username";
$lang['strPassword'] = "Password";
$lang['strAuthcode'] = "Authorization code";
$lang['strCountry'] = "Country";
$lang['strState'] = "State";
$lang['strCity'] = "City";
$lang['strZip'] = "ZIP/Postal code";
$lang['strAddress'] = "Street address";
$lang['strEmail'] = "E-mail";
$lang['strPhone'] = "Phone";
$lang['strWorkphone'] = "Phone work";
$lang['strCellular'] = "Cellular";
$lang['strCompany'] = "Company";
$lang['strDepartment'] = "Department";
$lang['strFunction'] = "Function";
$lang['strQuestion'] = "Secret question";
$lang['strAnswer'] = "Answer";
$lang['strFax'] = "Fax";
//$lang['strBusinessNum'] = "ID/Business number";
$lang['strWorkFax'] = "Fax work";
$lang['strHomepage'] = "Homepage";
$lang['strWorkAddress'] = "Address Work";
$lang['strWorkZip'] = "Zipcode work";
$lang['strWorkCountry'] = "Country work";
$lang['strWorkState'] = "State work";
$lang['strWorkCity'] = "City work";
$lang['strPhoto'] = "Photo";
$lang['strComments'] = "Comments";

$lang['strProperties'] = 'properties';

$lang['strDeleteItem'] = "Delete";

$lang['strDate'] = "Date";

$lang['strSaveSuccess'] = "Data saved successfully";
$lang['strSaveError'] = "An error occured while saving data. Please try again.";
$lang['strDataError'] = "An error occured while reading data. Please try reloading this page.";
$lang['strDeleteError'] = "Could not delete data.";
$lang['strAclError'] = "Access Control error";
$lang['strDateError'] = "You entered an invalid date";



$lang['strAccessDenied'] = "Access denied";
$lang['AccessDenied_text'] = "You are not allowed to view this section of the site or to perform this action.<br />Another user has restricted access to the information you requested.";

$lang['invalid_chars'] = "The following characters are not allowed";

$lang['strGroups'] = "Groups";
$lang['strOwner'] = "Owner";

$lang['strDeletePrefix'] = "Are you sure you want to delete ";
$lang['strDeleteSuffix'] = "?";

//menu
$lang['menu_minimize'] = "minimize";
$lang['menu_logout'] = "Logout";
$lang['menu_applications'] = "Applications";
$lang['menu_help'] = "Help";
$lang['menu_about'] = "About";
$lang['menu_documentation'] = "Documentation";
$lang['menu_configuration'] = "Configuration";
$lang['menu_groups'] = "User&nbsp;groups";
$lang['menu_accounts'] = "Your&nbsp;account";
$lang['menu_preferences'] = "Preferences";
$lang['menu_bookmarks'] = "Favorites";
$lang['menu_bookmarks_manage'] = "Modify&nbsp;favorites";
$lang['menu_add_bookmark'] = "Add&nbsp;a favorite";
$lang['menu_add_current'] = "add&nbsp;current&nbsp;page";
$lang['menu_contacts'] = "address book";
$lang['menu_invite'] = "invite&nbsp;users";
$lang['menu_search'] = "search";
$lang['menu_search_discussions'] = "discussions";
$lang['menu_search_files'] = "files&nbsp;and&nbsp;folders";
$lang['menu_search_web'] = "the&nbsp;web";
$lang['menu_scheduler'] = "Scheduler";
$lang['menu_filetypes'] = "File types";
$lang['menu_discussions'] = "discussion&nbsp;board";

$lang['menu_users'] = "Users";
//$lang['start'] = "Start";
$lang['menu_start'] = "Desktop";
$lang['menu_reboot'] = "reboot&nbsp;server";
$lang['menu_halt'] = "shutdown&nbsp;server";
$lang['menu_reboot_text'] = "WARNING! All Group-Office services will be temporarely unavailable. Are you sure you want to do continue?";
$lang['menu_halt_text'] = "WARNING! All Group-Office services will be terminated. Are you sure you want to do continue?";
$lang['menu_new'] = "new";
$lang['menu_message'] = "message";
$lang['menu_contact'] = "contact";
$lang['menu_event'] = "event";
$lang['menu_bookmark'] = "Favorites";
$lang['menu_topics'] = "topics";
$lang['menu_support'] = "Support";
$lang['menu_projects'] = "Projects";
$lang['menu_sysinfo'] = "System information";
$lang['menu_admin'] = 'Administrator';
$lang['menu_modules'] = 'Modules';
$lang['menu_manual'] = 'Manual';

//class validate
$lang['error_required'] = "You didn't specify the required field below.";
$lang['error_match_auth'] = "The authorisation codes didn't match.";
$lang['error_match_pass'] = "The passwords didn't match.";
$lang['error_min_length'] = "Minimum characters of the field below:";
$lang['error_max_length'] = "Maximum characters of the field below:";
$lang['error_email'] = "The E-mail address you specified was invalid.";
$lang['error_email_exists'] = "The E-mail address you entered already exists.";
$lang['error_username_exists'] = "Sorry, the username you entered already exists. Please choose another one.";
$lang['errors_in_form'] = "There were errors in the form. Correct them and try again.";
$lang['error_missing_field'] = "You didn't fill in all the required fields.";

//acl control
$lang['acl_control_auth_groups'] = "Authorized groups";
$lang['acl_control_auth_users'] = "Authorized users";
$lang['acl_control_no_contacts'] = "You don't have any member contacts to select.<br /> Use the Addressbook to add members to your contacts.";

$lang['strShowProfile'] = "View Profile";
$lang['strShowGroup'] = "View group members";
$lang['strProcessingTime'] = "The processing of this page took ";
$lang['strLoggedInAs'] = "Logged in as ";
$lang['strAt'] = " at ";
$lang['strEmailTo'] = "Send an E-mail message to: ";
$lang['strProtectedUser'] = "Protected User";

$lang['http_not_found'] = "Document not found";
$lang['http_not_found_text'] = "The requested document was not found. Maybe you mistyped the URL.";
$lang['http_error'] = "Internal Server Error";
$lang['http_bad_request'] = "Bad request";
$lang['strAddContact'] = "Add to contacts";

$lang['strReadRights'] = "Read permissions";
$lang['strWriteRights'] = "Write permissions";
$lang['strPermissions'] = 'permissions';

$lang['editor_bold'] = "Bold";
$lang['editor_italic'] = "Italic";
$lang['editor_underline'] = "Underline";
$lang['editor_left'] = "Left";
$lang['editor_right'] = "Right";
$lang['editor_center'] = "Center";
$lang['editor_ord_list'] = "Ordered List";
$lang['editor_bul_list'] = "Bulleted List";
$lang['editor_txt_color'] = "Text Color";
$lang['editor_back_color'] = "Background Color";
$lang['editor_hyperlink'] = "Hyperlink";
$lang['editor_image'] = "Image";
$lang['editor_rule'] = "Horizontal Rule";

$lang['editor_very_small'] = "Very small";
$lang['editor_small'] = "Small";
$lang['editor_medium'] = "Medium";
$lang['editor_large'] = "Large";
$lang['editor_larger'] = "Larger";
$lang['editor_very_large'] = "Very large";

$lang['editor_strikethrough'] = "Strike Through";
$lang['editor_outdent'] = "Outdent";
$lang['editor_indent'] = "Indent";

$lang['editor_superscript'] = "Superscript";
$lang['editor_subscript'] = "Subscript";
$lang['editor_undo'] = "Undo";
$lang['editor_redo'] = "Redo";
$lang['editor_copy'] = "Copy";
$lang['editor_paste'] = "Paste";
$lang['editor_cut'] = "Cut";

$lang['editor_font'] = "Font";
$lang['editor_size'] = "Size";
$lang['editor_heading'] = "Heading";
$lang['editor_select'] = "Select";

$lang['editor_mode'] = "Toggle editor mode";

$days[0]="Su";
$days[1]="Mo";
$days[2]="Tu";
$days[3]="We";
$days[4]="Th";
$days[5]="Fr";
$days[6]="Sa";

$months[0]="January";
$months[1]="February";
$months[2]="March";
$months[3]="April";
$months[4]="May";
$months[5]="June";
$months[6]="July";
$months[7]="August";
$months[8]="September";
$months[9]="October";
$months[10]="November";
$months[11]="December";

$full_days[0] = "Sunday";
$full_days[1] = "Monday";
$full_days[2] = "Tuesday";
$full_days[3] = "Wednesday";
$full_days[4] = "Thursday";
$full_days[5]= "Friday";
$full_days[6] = "Saturday";


$lang['register'] = "New user registration";
$lang['forgot_password'] = "Forgot your password?";
?>